# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: Airflow
on: [push]
env:
  BUILD_ID: ${{ github.sha }}
  MOUNT_LOCAL_SOURCES: "false"
  AIRFLOW_MOUNT_HOST_VOLUMES_FOR_STATIC_CHECKS: "true"
  FORCE_ANSWER_TO_QUESTIONS: "yes"
  AIRFLOW_CI_SILENT: "true"
  CI: "true"
  # Should be a target branch
  TRAVIS_BRANCH: "master"
  TRAVIS: "true"
jobs:
  statics:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Before install"
        env:
          PYTHON_VERSION: 3.6
          AIRFLOW_MOUNT_SOURCE_DIR_FOR_STATIC_CHECKS: "true"
          TRAVIS_JOB_NAME: "Static"
        run: ./scripts/ci/ci_before_install.sh
      - name: "Static checks"
        if: success()
        env:
          PYTHON_VERSION: 3.6
        run: chmod -x .github/workflows/ci.yml ; ./scripts/ci/ci_run_all_static_tests.sh

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build documentation"
        env:
          TRAVIS_JOB_NAME: "Build documentation"
          PYTHON_VERSION: 3.6
        run: ./scripts/ci/ci_docs.sh

  tests-k8s-persistent:
    name: "Tests [Postgres][3.6][Kubernetes][persistent]"
    runs-on: self-hosted
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Postgres][3.6][Kubernetes][persistent]"
        env:
          TRAVIS_JOB_NAME: "Tests [Postgres][3.6][Kubernetes][persistent]"
          BACKEND: postgres
          PYTHON_VERSION: 3.6
          RUNTIME: kubernetes
          ENABLE_KIND_CLUSTER: true
          KUBERNETES_MODE: persistent_mode
          KUBERNETES_VERSION: v1.15.3
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-k8s-git:
    name: "Tests [Postgres][3.7][Kubernetes][git]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Postgres][3.7][Kubernetes][git]"
        env:
          TRAVIS_JOB_NAME: "Tests [Postgres][3.7][Kubernetes][git]"
          BACKEND: postgres
          PYTHON_VERSION: 3.7
          RUNTIME: kubernetes
          ENABLE_KIND_CLUSTER: true
          KUBERNETES_MODE: git_mode
          KUBERNETES_VERSION: v1.15.3
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-p36-postgres-integrations:
    name: "Tests [Postgres][3.6][integrations]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Postgres][3.6][integrations]"
        env:
          TRAVIS_JOB_NAME: "Tests [Postgres][3.6][integrations]"
          BACKEND: postgres
          PYTHON_VERSION: 3.6
          ENABLED_INTEGRATIONS: "cassandra kerberos mongo openldap rabbitmq redis"
          RUN_INTEGRATION_TESTS: all
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-p36-postgres:
    name: "Tests [Postgres][3.6]"
    runs-on: self-hosted
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Postgres][3.6]"
        env:
          TRAVIS_JOB_NAME: "Tests [Postgres][3.6]"
          BACKEND: postgres
          PYTHON_VERSION: 3.6
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-p37-sqlite-integrations:
    name: "Tests [Sqlite][3.7][integrations]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Sqlite][3.7][integrations]"
        env:
          TRAVIS_JOB_NAME: "Tests [Sqlite][3.7][integrations]"
          BACKEND: sqlite
          PYTHON_VERSION: 3.7
          ENABLED_INTEGRATIONS: "cassandra kerberos mongo openldap rabbitmq redis"
          RUN_INTEGRATION_TESTS: all
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-p36-sqlite:
    name: "Tests [Sqlite][3.6]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [Sqlite][3.6]"
        env:
          TRAVIS_JOB_NAME: "Tests [Sqlite][3.6]"
          BACKEND: sqlite
          PYTHON_VERSION: 3.6
        run: ./scripts/ci/ci_run_airflow_testing.sh

  tests-p36-mysql-integrations:
    name: "Tests [MySQL][3.6][integrations]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [MySQL][3.6][integrations]"
        env:
          TRAVIS_JOB_NAME: "Tests [MySQL][3.6][integrations]"
          BACKEND: sqlite
          PYTHON_VERSION: 3.6
          ENABLED_INTEGRATIONS: "cassandra kerberos mongo openldap rabbitmq redis"
          RUN_INTEGRATION_TESTS: all
        run: ./scripts/ci/ci_run_airflow_testing.sh tests/tests_core.py

  tests-p37-mysql-kerberos:
    name: "Tests [MySQL][3.7][kerberos]"
    runs-on: ubuntu-latest
    needs: [statics, docs]
    steps:
      - uses: actions/checkout@master
      - name: "Tests [MySQL][3.7][kerberos]"
        env:
          TRAVIS_JOB_NAME: "Tests [MySQL][3.7][kerberos]"
          BACKEND: mysql
          ENABLED_INTEGRATIONS: "kerberos"
          PYTHON_VERSION: 3.7
        run: ./scripts/ci/ci_run_airflow_testing.sh
